### ISSUE TITLE
Add a support to create a service of type repository.

### ISSUE THREAD

**Issue by kedar9444** [SpartanX1/nestjs-files#1]
This will help the users to create a special type of service which will at as a repository. 
Many users would love to have it because standard patterns always keep your business logic and repository code in separate files.

#feature request

**Comment by kedar9444** [comment]
I have already written code for the same,  not able to test it on local due to some buffer issue, will generate pr in some time.

**Comment by SpartanX1** [comment]
Hi  @kedar9444 ,
First of all thanks for the request!  I went through your PR , and here are my thoughts.

1.  The command generate repository service so far only changes the class name which may be achieved through the generate service command itself, for eg providing the name "**CatRepository**" would generate the "**CatRepositoryService**" which may be enough

2.  Repository definition may differ based on which orm user is using. Maybe you can add a command  instead for generating a **typeorm** repository class with entity decorators ?

**Comment by SpartanX1** [comment]
https://github.com/typeorm/typeorm/blob/master/docs/active-record-data-mapper.md
