### ISSUE TITLE
Add More Files

### ISSUE THREAD

**Issue by denniarems** [SpartanX1/nestjs-files#5]
like repository,dto,entity......

**Comment by SpartanX1** [comment]
Hi @denniarems  can you give examples of what the files would look like as these type of files vary according to different databases

**Comment by darthgogy** [comment]
It will be great to wrap entire [Nest CLI](https://docs.nestjs.com/cli/overview). It has [generate](https://docs.nestjs.com/cli/usages#nest-generate) command for creating [libraries](https://docs.nestjs.com/cli/libraries), etc.

**Comment by bulolo** [comment]
create-role.dto.ts 
```
import { ApiProperty } from '@nestjs/swagger'
import { IsEmail, IsMobilePhone, IsNotEmpty, IsNumber, IsOptional, IsPhoneNumber, IsString, MaxLength, MinLength } from 'class-validator'

export class CreateRoleDto {
  
  @ApiProperty({ description: '名称', required: true })
  @IsString()
  name: string

  @ApiProperty({ description: '部门ID', required: false })
  @IsNumber()
  dept_id: number

  @ApiProperty({ description: '备注', required: false })
  @IsString()
  remark: string

}
```
